--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 08-Jun-21 9:47:14 PM
-- Server version: 5.5.5-10.4.17-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE sonakhali_school;

--
-- Drop table `registration`
--
DROP TABLE IF EXISTS registration;

--
-- Set default database
--
USE sonakhali_school;

--
-- Create table `registration`
--
CREATE TABLE registration (
  id int(11) NOT NULL AUTO_INCREMENT,
  regiNo int(11) DEFAULT NULL,
  nameInBangla varchar(100) DEFAULT NULL,
  nameInEnglish varchar(50) DEFAULT NULL,
  fatherName varchar(50) DEFAULT NULL,
  motherName varchar(50) DEFAULT NULL,
  gender varchar(10) DEFAULT NULL,
  dob varchar(20) DEFAULT NULL,
  contactNo varchar(11) DEFAULT NULL,
  email varchar(50) DEFAULT NULL,
  occupationDetails varchar(200) DEFAULT NULL,
  admissionClass varchar(10) DEFAULT NULL,
  admissionYear varchar(4) DEFAULT NULL,
  presentVillage varchar(50) DEFAULT NULL,
  presentGpo varchar(4) DEFAULT NULL,
  presentDist varchar(50) DEFAULT NULL,
  presentThana varchar(50) DEFAULT NULL,
  permanentVillage varchar(50) DEFAULT NULL,
  permanentGpo varchar(4) DEFAULT NULL,
  permanentDist varchar(50) DEFAULT NULL,
  permanentThana varchar(50) DEFAULT NULL,
  sscYear varchar(4) DEFAULT NULL,
  sscInst varchar(100) DEFAULT NULL,
  hscYear varchar(4) DEFAULT NULL,
  hscInst varchar(100) DEFAULT NULL,
  gradYear varchar(4) DEFAULT NULL,
  gradInst varchar(100) DEFAULT NULL,
  mastersYear varchar(4) DEFAULT NULL,
  mastersInst varchar(100) DEFAULT NULL,
  dropOutClass varchar(10) DEFAULT NULL,
  dropOutYear varchar(4) DEFAULT NULL,
  feeAmount varchar(7) DEFAULT NULL,
  paymentDate varchar(15) DEFAULT NULL,
  schoolBkashNo varchar(11) DEFAULT NULL,
  senderBkashNo varchar(11) DEFAULT NULL,
  appliedDatetime datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table registration
--
-- Table sonakhali_school.registration does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;